/** Re-exports RadarScope palette utilities (legacy import path). */
export {
  type ColorStop,
  type PalFile,
  DEFAULT_PAL_STOPS,
  DEFAULT_PAL_STOPS as DEFAULT_CUSTOM_STOPS,
  PAL_DBZ_MIN,
  PAL_DBZ_MAX,
  PAL_DBZ_STEP,
  hexToRgb,
  rgbToHex,
  dbzToBarPercent,
  barPercentToDbz,
  colorAtDbz,
  colorAtReflectivityDbz,
  sortedColorStops,
  stopsToDbzUint32LUT,
  paletteCacheKey,
  reflectivityLowDbzFade,
  normalizeReflectivityFade,
  DEFAULT_REFLECTIVITY_FADE,
  type ReflectivityFadeSettings,
  rainViewerByteToDbz,
  stopsToRainViewerLUT,
  stopsToLuminanceLUT,
  stopsToCss,
  stopsValueSpan,
  parsePal,
  serializePal,
  fromWindyJson,
} from "./palPalette";
export { stopsToIemIndexLUT, iemIndexToDbz, iemRgbToIndex } from "./iemColormap";
