/** Auto-generated OPERA station mapping (EU station id → MeteoGate location). */
export interface OperaStationMeta {
  odim: string;
  locationId: string;
  namingAuthority: string;
}

export const OPERA_STATION_MAP: Record<string, OperaStationMeta> = {
  "dwd_boo": { odim: "deboo", locationId: "0-276-0-deboo", namingAuthority: "de.dwd" },
  "dwd_ros": { odim: "deros", locationId: "0-276-0-deros", namingAuthority: "de.dwd" },
  "dwd_eis": { odim: "deeis", locationId: "0-276-0-deeis", namingAuthority: "de.dwd" },
  "dwd_ess": { odim: "deess", locationId: "0-276-0-deess", namingAuthority: "de.dwd" },
  "dwd_fbg": { odim: "defbg", locationId: "0-276-0-defbg", namingAuthority: "de.dwd" },
  "dwd_fld": { odim: "defld", locationId: "0-276-0-defld", namingAuthority: "de.dwd" },
  "dwd_ham": { odim: "deboo", locationId: "0-276-0-deboo", namingAuthority: "de.dwd" },
  "dwd_hnr": { odim: "dehnr", locationId: "0-276-0-dehnr", namingAuthority: "de.dwd" },
  "dwd_mem": { odim: "demem", locationId: "0-276-0-demem", namingAuthority: "de.dwd" },
  "dwd_mhp": { odim: "deisn", locationId: "0-276-0-deisn", namingAuthority: "de.dwd" },
  "dwd_neu": { odim: "deneu", locationId: "0-276-0-deneu", namingAuthority: "de.dwd" },
  "dwd_nhb": { odim: "denhb", locationId: "0-276-0-denhb", namingAuthority: "de.dwd" },
  "dwd_oft": { odim: "deoft", locationId: "0-276-0-deoft", namingAuthority: "de.dwd" },
  "dwd_pro": { odim: "depro", locationId: "0-276-0-depro", namingAuthority: "de.dwd" },
  "dwd_umd": { odim: "deumd", locationId: "0-276-0-deumd", namingAuthority: "de.dwd" },
  "dwd_drs": { odim: "dedrs", locationId: "0-276-0-dedrs", namingAuthority: "de.dwd" },
  "fr_abbeville": { odim: "frabb", locationId: "0-20010-0-07005", namingAuthority: "fr.meteofrance" },
  "fr_arcis": { odim: "frtro", locationId: "0-21010-0-51", namingAuthority: "fr.meteofrance" },
  "fr_avesnois": { odim: "frave", locationId: "0-20010-0-07083", namingAuthority: "fr.meteofrance" },
  "fr_bordeaux": { odim: "frbor", locationId: "0-20010-0-07510", namingAuthority: "fr.meteofrance" },
  "fr_brest": { odim: "frpla", locationId: "0-20010-0-07108", namingAuthority: "fr.meteofrance" },
  "fr_collobrières": { odim: "frcol", locationId: "0-20010-0-07671", namingAuthority: "fr.meteofrance" },
  "fr_paris": { odim: "frtra", locationId: "0-20010-0-07145", namingAuthority: "fr.meteofrance" },
  "fr_nimes": { odim: "frnim", locationId: "0-20010-0-07658", namingAuthority: "fr.meteofrance" },
  "fr_toulouse": { odim: "frtou", locationId: "0-20010-0-07629", namingAuthority: "fr.meteofrance" },
  "nl_den_helder": { odim: "nldhl", locationId: "0-578-0-nldhl", namingAuthority: "nl.knmi" },
  "nl_herwijnen": { odim: "nlhrw", locationId: "0-578-0-nlhrw", namingAuthority: "nl.knmi" },
  "be_jabbeke": { odim: "bejab", locationId: "0-578-0-bejab", namingAuthority: "be.rmi" },
  "be_wideumont": { odim: "bewid", locationId: "0-578-0-bewid", namingAuthority: "be.rmi" },
  "ch_albis": { odim: "chalb", locationId: "0-20000-0-06661", namingAuthority: "ch.meteoswiss" },
  "ch_dole": { odim: "chdol", locationId: "0-20000-0-06699", namingAuthority: "ch.meteoswiss" },
  "ch_lema": { odim: "chlem", locationId: "0-20000-0-06768", namingAuthority: "ch.meteoswiss" },
  "ch_plaine": { odim: "chppm", locationId: "0-20000-0-06726", namingAuthority: "ch.meteoswiss" },
  "se_ank": { odim: "seang", locationId: "0-20000-0-2606", namingAuthority: "se.smhi" },
  "se_hud": { odim: "sehuv", locationId: "0-20000-0-2334", namingAuthority: "se.smhi" },
  "se_kir": { odim: "sekrn", locationId: "0-20000-0-2032", namingAuthority: "se.smhi" },
  "se_lla": { odim: "sella", locationId: "0-20000-0-2092", namingAuthority: "se.smhi" },
  "se_oer": { odim: "seoer", locationId: "0-20000-0-2262", namingAuthority: "se.smhi" },
  "se_osd": { odim: "seosd", locationId: "0-20000-0-2200", namingAuthority: "se.smhi" },
  "se_var": { odim: "sevax", locationId: "0-20000-0-2600", namingAuthority: "se.smhi" },
  "no_andoy": { odim: "noand", locationId: "0-578-0-noand", namingAuthority: "no.met" },
  "no_berlevaag": { odim: "nober", locationId: "0-578-0-nober", namingAuthority: "no.met" },
  "no_hurum": { odim: "nohur", locationId: "0-578-0-nohur", namingAuthority: "no.met" },
  "no_rissa": { odim: "norsa", locationId: "0-578-0-norsa", namingAuthority: "no.met" },
  "no_stad": { odim: "nosta", locationId: "0-578-0-nosta", namingAuthority: "no.met" },
  "fi_anjalankoski": { odim: "fianj", locationId: "0-20010-0-02954", namingAuthority: "fi.fmi" },
  "fi_kesalahti": { odim: "fikes", locationId: "0-20010-0-02995", namingAuthority: "fi.fmi" },
  "fi_korpo": { odim: "fikor", locationId: "0-20010-0-02933", namingAuthority: "fi.fmi" },
  "fi_kuopio": { odim: "fikuo", locationId: "0-20010-0-02918", namingAuthority: "fi.fmi" },
  "fi_luosto": { odim: "filuo", locationId: "0-20010-0-02840", namingAuthority: "fi.fmi" },
  "fi_petajavesi": { odim: "fipet", locationId: "0-20010-0-02775", namingAuthority: "fi.fmi" },
  "fi_utajarvi": { odim: "fiuta", locationId: "0-20010-0-02870", namingAuthority: "fi.fmi" },
  "fi_vantaa": { odim: "fivan", locationId: "0-578-0-fivan", namingAuthority: "fi.fmi" },
  "fi_vimpeli": { odim: "fivim", locationId: "0-20010-0-02925", namingAuthority: "fi.fmi" },
  "dk_bornholm": { odim: "dkbor", locationId: "0-578-0-dkbor", namingAuthority: "dk.dmi" },
  "dk_romo": { odim: "dkrom", locationId: "0-578-0-dkrom", namingAuthority: "dk.dmi" },
  "dk_sindal": { odim: "dksin", locationId: "0-578-0-dksin", namingAuthority: "dk.dmi" },
  "dk_stevns": { odim: "dkste", locationId: "0-578-0-dkste", namingAuthority: "dk.dmi" },
  "dk_virring": { odim: "dkvir", locationId: "0-578-0-dkvir", namingAuthority: "dk.dmi" },
  "es_almeria": { odim: "esalm", locationId: "0-578-0-esalm", namingAuthority: "es.aemet" },
  "es_barcelona": { odim: "esbar", locationId: "0-578-0-esbar", namingAuthority: "es.aemet" },
  "es_bilbao": { odim: "essse", locationId: "0-578-0-essse", namingAuthority: "es.aemet" },
  "es_madrid": { odim: "esmad", locationId: "0-578-0-esmad", namingAuthority: "es.aemet" },
  "es_malaga": { odim: "esmal", locationId: "0-578-0-esmal", namingAuthority: "es.aemet" },
  "es_sevilla": { odim: "essev", locationId: "0-578-0-essev", namingAuthority: "es.aemet" },
  "es_valencia": { odim: "esval", locationId: "0-578-0-esval", namingAuthority: "es.aemet" },
  "es_zaragoza": { odim: "eszar", locationId: "0-578-0-eszar", namingAuthority: "es.aemet" },
  "pl_gdansk": { odim: "plgda", locationId: "0-578-0-plgda", namingAuthority: "pl.imgw" },
  "pl_legionowo": { odim: "plleg", locationId: "0-20000-0-12374", namingAuthority: "pl.imgw" },
  "pl_poznan": { odim: "plpoz", locationId: "0-20000-0-12331", namingAuthority: "pl.imgw" },
  "pl_rzeszow": { odim: "plrze", locationId: "0-20000-0-12579", namingAuthority: "pl.imgw" },
  "pl_swidwin": { odim: "plswi", locationId: "0-20000-0-12220", namingAuthority: "pl.imgw" },
  "ie_castor_bay": { odim: "iesha", locationId: "0-578-0-iesha", namingAuthority: "ie.met" },
  "ie_dublin": { odim: "iedub", locationId: "0-578-0-iedub", namingAuthority: "ie.met" },
};
